version: "2"

services:
  goip-sms-server:
    image: bzmn/goip-sms-server
    container_name: goip-sms-server
    restart: always
    network_mode: bridge
    ports:
      - 44444:44444/udp
      - 8086:80
    environment:
      - MYTIMEZONE=Europe/Kiev
      - GOIP_WEB_LOGIN=smsadmin
      - GOIP_WEB_PASSWORD=mysuperCoOlpassXX1
      - MYSQL_MAIN_HOST=10.0.15.4
      - MYSQL_MAIN_PORT=3307
      - MYSQL_MAIN_DB=goip
      - MYSQL_MAIN_LOGIN=root
      - MYSQL_MAIN_PASSWORD=123456
