version: "2"

services:
  goip-sms-server:
    image: bzmn/goip-sms-server
    container_name: goip-sms-server
    restart: always
    network_mode: bridge
    ports:
      - 44444:44444/udp
      - 8086:80
    environment:
      - MYTIMEZONE=${MYTIMEZONE}
      - GOIP_WEB_LOGIN=${GOIP_WEB_LOGIN}
      - GOIP_WEB_PASSWORD=${GOIP_WEB_PASSWORD}
      - MYSQL_MAIN_HOST=${DB_HOST}
      - MYSQL_MAIN_PORT=${DB_PORT}
      - MYSQL_MAIN_DB=${DB_NAME}
      - MYSQL_MAIN_LOGIN=${DB_USER}
      - MYSQL_MAIN_PASSWORD=${MYSQL_ROOT_PASSWORD}
